name: Haskell lab1 tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: hlint src

  format:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - run: ormolu --mode check src/*.hs

  test:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: stack test
